title: Carmen Ng  # You can add your name here

logo: carmen_ng_headshot_222x225.jpg # Use a relative path to logo image 

description: Hong Kong native based in Europe, with international, cross-sector experience in AI ethics research, journalism, and climate technology. Blending policy acumen, cross-disciplinary knowledge and computational skills in fostering intercultural fairness in AI development. 

See my <a href="Library.html">Library</a> for a snapshort of my work. # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: carmen.ng@tum.de # Allow visitors to contact you

# Navigation links
header_pages:
  - index.md
  - my-work.md
